# 'tomcat' Folder Structure
# /usr/local/tomcat
FROM myself/mytomcat:0.1
MAINTAINER Daniele Demichelis <demichelis@danidemi.com>

# COPY cannot reference files outside the folder we are runnin in
COPY *.war /usr/local/tomcat/webapps/
 