# This docker image extends the official 'tomcat' adding manager access to the users
# defined in the xml file.
FROM tomcat
MAINTAINER Daniele Demichelis <demichelis@danidemi.com>
COPY tomcat-users.xml /usr/local/tomcat/conf/tomcat-users.xml

